name: Deploy to Firebase

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
  pull_request:
    branches:
      - main  # or master, depending on your default branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
      
    - name: Debug Secret
      run: |
        echo "Checking if secret exists..."
        if [ -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISHU_BREAKFAST_RECIPES }}" ]; then
          echo "Secret exists and has length: $(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISHU_BREAKFAST_RECIPES }}' | wc -c)"
          echo "First 50 characters of secret: $(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISHU_BREAKFAST_RECIPES }}' | cut -c1-50)"
          echo "Secret type: $(echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISHU_BREAKFAST_RECIPES }}' | jq -r 'type')"
        else
          echo "Secret is empty or not set"
        fi
    
    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main'  # Only deploy on main branch
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AISHU_BREAKFAST_RECIPES }}'
        channelId: live
        projectId: aishu-breakfast-recipes
      env:
        FIREBASE_CLI_EXPERIMENTS: webframeworks
    
    - name: Notify Deployment
      if: success()
      run: |
        echo "Deployment successful! 🚀"
        echo "Site URL: https://aishu-breakfast-recipes.web.app" 